using System.Net;
using System.Text.Json;
using Design.ORiN3.Provider.V1.Base;
using Design.ORiN3.RemoteEngineEx.V1;
using Google.Protobuf;
using Grpc.Net.Client;
using Message.Client.ORiN3.Provider.V1;
using Message.ORiN3.Provider.V1.AutoGenerated;
using Message.ORiN3.Provider.V1.AutoGenerated.Variable;
using Message.Client.ORiN3.RemoteEngine.V1;

namespace ChatAppAI.McpServer.Services;

public sealed record ProviderProcessInfo(Guid Id, string Name, string Version, int Pid, string ProviderId);

public sealed record AvailableProviderInfo(
    string Id,
    string Version,
    string Title,
    string Description,
    string Authors,
    string ProjectUrl,
    string ProviderConfigData);

public sealed record ManualLink(string Text, string Uri);

public sealed record ProviderManual(string Uri, string Culture, string Text, IReadOnlyList<ManualLink> Links);

public sealed record ProviderVariableValue(
    string ProviderUri,
    string ControllerId,
    string ControllerName,
    string VariableId,
    string VariableName,
    string ValueType,
    object? Value);

public sealed class RemoteEngineService(IHttpClientFactory httpClientFactory)
{
    private const uint TimeoutIntervalMilliseconds = 10_000;
    private readonly IHttpClientFactory _httpClientFactory = httpClientFactory;

    public async Task<IReadOnlyList<AvailableProviderInfo>> ListProvidersAsync(
        string remoteEngineUri,
        string? providerName,
        CancellationToken cancellationToken)
    {
        return await ExecuteAsync(remoteEngineUri, async client =>
        {
            var providers = new List<AvailableProviderInfo>();
            await foreach (var result in client.GetAvailableProvidersAsync(GetAvailableProvidersOption.All, cancellationToken))
            {
                var package = result.ProviderPackageInfo;
                if (string.IsNullOrWhiteSpace(package.Id) ||
                    (!string.IsNullOrWhiteSpace(providerName) && !MatchesProviderName(package, providerName)))
                {
                    continue;
                }

                providers.Add(new AvailableProviderInfo(
                    package.Id,
                    package.Version,
                    package.Title,
                    package.Description,
                    package.Authors,
                    package.ProjectUrl,
                    result.ProviderConfigData));
            }

            return providers;
        }, cancellationToken).ConfigureAwait(false);
    }

    public async Task<ProviderProcessInfo> ResolveProviderAsync(
        string remoteEngineUri,
        string? providerName,
        int? pid,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(providerName) && pid is null)
        {
            throw new ArgumentException("providerName または pid のどちらかを指定してください。");
        }

        var providers = await ListRunningProvidersAsync(remoteEngineUri, providerName, cancellationToken).ConfigureAwait(false);
        var provider = pid is not null
            ? providers.FirstOrDefault(item => item.Pid == pid.Value)
            : providers.FirstOrDefault();

        return provider ?? throw new InvalidOperationException("指定されたプロバイダーを特定できませんでした。");
    }

    private static bool MatchesProviderName(IProviderPackageInfo package, string providerName)
    {
        return package.Id.Contains(providerName, StringComparison.OrdinalIgnoreCase) ||
            package.Title.Contains(providerName, StringComparison.OrdinalIgnoreCase) ||
            package.Description.Contains(providerName, StringComparison.OrdinalIgnoreCase) ||
            package.Tags.Contains(providerName, StringComparison.OrdinalIgnoreCase);
    }

    private async Task<IReadOnlyList<ProviderProcessInfo>> ListRunningProvidersAsync(
        string remoteEngineUri,
        string? providerName,
        CancellationToken cancellationToken)
    {
        return await ExecuteAsync(remoteEngineUri, async client =>
        {
            var providers = new List<ProviderProcessInfo>();
            await foreach (var provider in client.ListProviderProcessAsync(providerName ?? string.Empty, cancellationToken))
            {
                providers.Add(new ProviderProcessInfo(provider.Id, provider.Name, provider.Version, provider.Pid, provider.ProviderId));
            }

            return providers;
        }, cancellationToken).ConfigureAwait(false);
    }

    public async Task TerminateProviderAsync(
        string remoteEngineUri,
        string? providerName,
        int? pid,
        CancellationToken cancellationToken)
    {
        var provider = await ResolveProviderAsync(remoteEngineUri, providerName, pid, cancellationToken).ConfigureAwait(false);
        await ExecuteAsync(
            remoteEngineUri,
            async client =>
            {
                await client.TerminateProviderAsync(provider.Id, cancellationToken).ConfigureAwait(false);
                return true;
            },
            cancellationToken).ConfigureAwait(false);
    }

    public async Task<ProviderManual> GetProviderManualAsync(
        string remoteEngineUri,
        string providerId,
        string version,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(providerId);
        ArgumentException.ThrowIfNullOrWhiteSpace(version);

        var manualUris = await ExecuteAsync(
            remoteEngineUri,
            client => client.GetManualUrisAsync(cancellationToken),
            cancellationToken).ConfigureAwait(false);

        var orderedUris = manualUris
            .Select(TryCreateManualBaseUri)
            .Where(uri => uri is not null)
            .Select(uri => uri!)
            .OrderByDescending(uri => uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase));

        var cultures = new[] { "ja", "default", "en" };
        foreach (var baseUri in orderedUris)
        {
            foreach (var culture in cultures)
            {
                var manualUri = BuildProviderManualUri(baseUri, providerId, version, culture);
                try
                {
                    using var response = await _httpClientFactory.CreateClient().GetAsync(manualUri, cancellationToken).ConfigureAwait(false);
                    if (!response.IsSuccessStatusCode)
                    {
                        continue;
                    }

                    if (response.RequestMessage?.RequestUri is not Uri resolvedUri || !IsUnderManualRoot(resolvedUri, baseUri))
                    {
                        continue;
                    }

                    var html = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                    return ParseManual(manualUri, baseUri, culture, html);
                }
                catch (HttpRequestException)
                {
                }
                catch (TaskCanceledException) when (!cancellationToken.IsCancellationRequested)
                {
                }
            }
        }

        throw new HttpRequestException("利用可能な provider マニュアル endpoint が見つかりませんでした。");
    }

    public async Task<ProviderVariableValue> GetProviderVariableValueAsync(
        string providerUri,
        string controllerName,
        string variableName,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(controllerName);
        ArgumentException.ThrowIfNullOrWhiteSpace(variableName);

        var endpoint = ValidateEndpointUri(providerUri, nameof(providerUri));
        using var channel = GrpcChannel.ForAddress(endpoint);
        using var rootObject = await ORiN3RootObject.AttachAsync(channel, TimeoutIntervalMilliseconds, cancellationToken).ConfigureAwait(false);

        var controllerInformation = await FindSingleChildAsync(rootObject, controllerName, "Controller", cancellationToken).ConfigureAwait(false);
        var controller = await rootObject.GetChildAsync(controllerInformation.Id, cancellationToken).ConfigureAwait(false);
        if (controller is not IParent controllerParent)
        {
            throw new InvalidOperationException($"'{controllerName}' は Controller ではありません。");
        }

        var variableInformation = await FindSingleChildAsync(controllerParent, variableName, "Variable", cancellationToken).ConfigureAwait(false);
        var client = new VariableService.VariableServiceClient(channel);
        var response = await client.GetValueAsync(
            new GetValueRequest
            {
                Id = ByteString.CopyFrom(variableInformation.Id.ToByteArray())
            },
            deadline: DateTime.UtcNow.AddMilliseconds(TimeoutIntervalMilliseconds),
            cancellationToken: cancellationToken).ResponseAsync.ConfigureAwait(false);

        if (!string.Equals(response.Common?.ResultCode.ToString(), "Succeeded", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Variable '{variableName}' の GetValue に失敗しました: {response.Common?.ResultCode} {response.Common?.Detail}");
        }

        if (response.Value is null)
        {
            throw new InvalidOperationException($"Variable '{variableName}' の GetValue 応答に値が含まれていません。");
        }

        return new ProviderVariableValue(
            endpoint.ToString(),
            controllerInformation.Id.ToString(),
            controllerInformation.Name,
            variableInformation.Id.ToString(),
            variableInformation.Name,
            response.Value.Type.ToString(),
            ConvertProviderValue(response.Value));
    }

    private static async Task<Design.ORiN3.Provider.V1.Base.IORiN3ObjectInformation> FindSingleChildAsync(
        IParent parent,
        string name,
        string objectType,
        CancellationToken cancellationToken)
    {
        var matches = (await parent.GetChildInformationsAsync(cancellationToken).ConfigureAwait(false))
            .Where(child =>
                string.Equals(child.Name, name, StringComparison.Ordinal) &&
                string.Equals(child.ORiN3ObjectType.ToString(), objectType, StringComparison.Ordinal))
            .ToArray();

        return matches.Length switch
        {
            1 => matches[0],
            0 => throw new InvalidOperationException($"名前 '{name}' の {objectType} が見つかりませんでした。"),
            _ => throw new InvalidOperationException($"名前 '{name}' の {objectType} が複数見つかりました。ID を指定できるツールで対象を一意にしてください。")
        };
    }

    private static object? ConvertProviderValue(ORiN3Value value)
    {
        var valueProperty = value.GetType().GetProperty(value.ValueCase.ToString());
        var wrappedValue = valueProperty?.GetValue(value);
        if (wrappedValue is null)
        {
            return JsonDocument.Parse(value.ToString()).RootElement.Clone();
        }

        var isNull = wrappedValue.GetType().GetProperty("IsNull")?.GetValue(wrappedValue) as bool?;
        if (isNull is true)
        {
            return null;
        }

        return wrappedValue.GetType().GetProperty("RawValue")?.GetValue(wrappedValue)
            ?? JsonDocument.Parse(value.ToString()).RootElement.Clone();
    }

    private static Uri? TryCreateManualBaseUri(string uriString)
    {
        if (!Uri.TryCreate(uriString, UriKind.Absolute, out var uri) ||
            (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps) ||
            !string.IsNullOrEmpty(uri.UserInfo) ||
            !string.IsNullOrEmpty(uri.Query) ||
            !string.IsNullOrEmpty(uri.Fragment))
        {
            return null;
        }

        return uri;
    }

    private static Uri BuildProviderManualUri(Uri baseUri, string providerId, string version, string culture)
    {
        var root = baseUri.AbsoluteUri.TrimEnd('/') + "/manual/provider/";
        return new Uri($"{root}{Uri.EscapeDataString(providerId)}/{Uri.EscapeDataString(version)}/{culture}/", UriKind.Absolute);
    }

    private static bool IsUnderManualRoot(Uri uri, Uri baseUri)
    {
        var manualRoot = baseUri.AbsoluteUri.TrimEnd('/') + "/manual/";
        return uri.Scheme == baseUri.Scheme &&
            uri.Host.Equals(baseUri.Host, StringComparison.OrdinalIgnoreCase) &&
            uri.Port == baseUri.Port &&
            uri.AbsolutePath.StartsWith(new Uri(manualRoot).AbsolutePath, StringComparison.OrdinalIgnoreCase);
    }

    private static ProviderManual ParseManual(Uri uri, Uri baseUri, string culture, string html)
    {
        var document = new HtmlAgilityPack.HtmlDocument();
        document.LoadHtml(html);

        var text = WebUtility.HtmlDecode(document.DocumentNode.InnerText).Trim();
        var links = document.DocumentNode
            .SelectNodes("//a[@href]")?
            .Select(anchor =>
            {
                var linkUri = new Uri(uri, anchor.GetAttributeValue("href", string.Empty));
                return new ManualLink(WebUtility.HtmlDecode(anchor.InnerText).Trim(), linkUri.ToString());
            })
            .Where(link => Uri.TryCreate(link.Uri, UriKind.Absolute, out var linkUri) && IsUnderManualRoot(linkUri, baseUri))
            .DistinctBy(link => link.Uri)
            .ToArray() ?? [];

        return new ProviderManual(uri.ToString(), culture, text, links);
    }

    private static async Task<TResult> ExecuteAsync<TResult>(
        string remoteEngineUri,
        Func<IRemoteEngineEx, Task<TResult>> operation,
        CancellationToken cancellationToken)
    {
        var endpoint = ValidateEndpointUri(remoteEngineUri, nameof(remoteEngineUri));

        using var channel = GrpcChannel.ForAddress(endpoint);
        using var client = await RemoteEngine.AttachAsync(channel, TimeoutIntervalMilliseconds, cancellationToken).ConfigureAwait(false);
        return await operation(client).ConfigureAwait(false);
    }

    private static Uri ValidateEndpointUri(string uri, string parameterName)
    {
        if (!Uri.TryCreate(uri, UriKind.Absolute, out var endpoint) ||
            (endpoint.Scheme != Uri.UriSchemeHttp && endpoint.Scheme != Uri.UriSchemeHttps) ||
            !string.IsNullOrEmpty(endpoint.UserInfo) ||
            !string.IsNullOrEmpty(endpoint.Query) ||
            !string.IsNullOrEmpty(endpoint.Fragment))
        {
            throw new ArgumentException($"{parameterName} には http または https の URI を指定してください。", parameterName);
        }

        return endpoint;
    }
}